micronaut:
  application:
    name: bancha-library
  server:
    port: 8081
---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:`abc`}
  secretKeyId: ${AWS_SECRET_KEY_ID:`xyz`}
  rds:
    url: ${AWS_RDS_URL:`http://localhost:8080`}
    region: ${AWS_RDS_REGION:`us-east-1`}
    database: ${AWS_RDS_DATABASE:`db`}
    resourceArn: ${AWS_RDS_RESOURCE_ARN:`arn:aws:rds:us-east-1:123456789012:cluster:dummy`}
    secretArn: ${AWS_RDS_SECRET_ARN:`arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy`}
